### PR TITLE
Eliminate separate plugin progress bar...

### PR DESCRIPTION
**Pull request by Dim3nsioneer**
... for newly released plugins and use Cura's built-in progress bar for both the CuraEngine and plugins.

Including an upgraded version of the TweakAtZ plugin.
It's backward compatible with recently released plugins.

### CODE REVIEW

**Comment by Dim3nsioneer** [comment]
Any more information needed?

**Comment by daid** [comment]
Oh, sorry, was this flying on my radar for some weeks. I did look at it initially.

Didn't like the default "CuraEngine" message too much, might confuse the "basic" users who never use plugins and are suddenly met with a "useless" CuraEngine message on their screen.

**Comment by Dim3nsioneer** [comment]
Well, first I wanted to write a label 'The greatest slicer engine in the World' but then I realised it was a bit too long.
Seriously: I see your point and removed that part.

**Comment by daid** [comment]
Looks fine now. (Do remember that the pubsub mechanism doesn't seem to work on MacOS)

**Comment by Dim3nsioneer** [comment]
Thanks! As far as I remember it is handled in the code, isn't it? I definitively added the check to the plugins which use the publisher class. If you think I missed a spot, please let me know.

**Pull request merged**
