### PR TITLE
TweakAtZ V3.99 RC2

### PR DESCRIPTION
**Pull request by Dim3nsioneer**
Hi Daid

For the case you want to include the latest development of the TweakAtZ plugin in another RC of Cura, you may merge the request. Otherwise please just close it. Including the TweakAtZ RC in the Cura RC would allow more users to test it.
Possible scenarios:
- The RC works as it should: I will issue an new pull request with the finite version 4.0 and delete the 3.99RC2
- The RC doesn't work properly: leave it as it is (that's why I changed the filename) or revert the pull request.

cheers
Stefan

### CODE REVIEW

**Comment by Dim3nsioneer** [comment]
@daid : Any idea yet what you will do with this pull request...? ;-)

**Comment by daid** [comment]
I think having 2 differnt versions of the plugin at once will confuse people. Any bugs you are afraid of in the version 4?

**Comment by Dim3nsioneer** [comment]
I also see some potential for confusing people. In my tests, the new version ran properly. From my point of view, I would risk it. If there is still an unkown bug inside, I can provide a quick bugfix via Github.

**Comment by daid** [comment]
Then i think we best just merge it into the default tweakatz.

**Pull request closed without merging**
