### PR TITLE
TweakAtZ 4.0.1

### PR DESCRIPTION
**Pull request by Dim3nsioneer**
Bugfix for doubled G1 commands with TweakAtZ

### CODE REVIEW

**Comment by daid** [comment]
How bad is this bug? Is it cosmetic or will it cause horrible problems?

**Comment by Dim3nsioneer** [comment]
The tweaking of the print speed might not work properly and every G1 command is written twice. Marlin for instance would simply drop the second of those as the distance between them is zero. I would consider it as cosmetic. The bugfix should be included in future versions.

**Comment by robotgof** [comment]
I ran across this and had multiple TweakAtZ's for different heights.  Each one doubled the code so I ended up with 128 copies of each move.

**Comment by Dim3nsioneer** [comment]
@robotgof : Please try V4.0.1: https://github.com/Dim3nsioneer/Cura-Plugins/raw/released/TweakAtZ.py

**Comment by robotgof** [comment]
Thanks. I already pulled it and tested it.  Everything looks good now.  The only reason I added my comment was to note that multiple instances of TweakAtZ resulted in 2^n duplicates.  Nothing like a 38MB gcode file for a simple hollow square column!  After installing 4.01 it dropped to 300k.

**Pull request merged**
