### PR TITLE
Working armhf build on ODROID-U3 running Ubuntu 14.04.1

### PR DESCRIPTION
**Pull request by rcarmo**
Hello there,

Here are the (relatively minor) changes I made to get Cura running on an [ODROID](http://www.hardkernel.com/main/products/prdt_info.php?g_code=G138745696275) quad-core ARM board running Ubuntu 14.04.1. They should also be applicable to people running Ubuntu (or an Ubuntu chroot) on other development boards, Chromebooks, etc.

### CODE REVIEW

**Comment by daid** [comment]
Cool stuff!

**Comment by rcarmo** [comment]
It was actually pretty straightforward. The only real issue I had was getting OpenGL to work right in my X server, and that had absolutely nothing to do with Cura (but is worth noting here for future reference, since GL support on ARM boards is still a bit hit and miss and any fixes will always be board-specific).

Also worth noting is that this _might_ work on a Raspberry Pi, but I didn't have the heart to even try given its limited CPU (the ODROID has a quad-core CPU, which helps considerably, but is still not on a par with Intel boxes for complex models).=

**Comment by daid** [comment]
The engine of Cura works quite fine on the Pi. People have been using this in combination with OctoPrint. But running the whole GUI is a different level. I'm surprised that you managed to pull this off, as I think most ARM based OpenGL implementation as OpenGL SE, which my code isn't written for at all.

**Comment by rcarmo** [comment]
The U3 has a number of different driver builds available for its mali chipset, but so far only really works nicely (i.e., without locking up X) with software rendering. It has a bigger cousin (the XU) with more OpenGL features, which I intend to try out soon...=

**Comment by daid** [comment]
Long time no update.

A friend of mine got a older chromebook, on which he installed Ubuntu (with some magic, not sure how). And he's wondering if he can run Cura on it. Would the package you build run on this?

**Comment by rcarmo** [comment]
It should. Depends more on the Ubuntu version than anything else (last time I fiddled with an ARM Chromebook, the LTS version was 12.04).

**Comment by REulberg** [comment]
I've been bumbling along trying to get the full Cura GUI running on the new raspberry Pi 2...
got most of the way there, but ran into this:
make: **\* No rule to make target '_UltimakerMarlin_250000/wiring.o', needed by '_UltimakerMarlin_250000/Marlin.elf'

not really sure where to go to continue. any suggestions?

**Comment by daid** [comment]
That's the firmware build, I recommend commenting those out in the package.sh script, as you don't really need them (you would need the arduino environment to build them)

**Comment by REulberg** [comment]
Thanks!
I was planning on getting the arduino environment put on anyway.
also needed python opengl
all appears to be working now, awesome!

**Comment by rcarmo** [comment]
That's great to hear. I might try this on a Pi 2 as well and confirm the steps required (my current setup relies on a hacked Mesa, would love something cleaner and easier to reproduce).

**Comment by daid** [comment]
That's amazing and surprising at the same time! But great work! (I do so many strange OpenGL legacy and new stuff mixing that I'm surprised it works at all sometimes)

**Pull request merged**
