### PR TITLE
Faster virtualprinter

### PR DESCRIPTION
**Pull request by hg42**
makes the VirtualPrinter much faster by reducing the sleep time

### CODE REVIEW

**Comment by daid** [comment]
Note, all your commits, even commits after you made a pull request, end up in the same pull request. So all your pulls are merged with this one.

**Comment by daid** [comment]
Awesome work :D

**Comment by hg42** [comment]
thanks, all parta were there so I simply rearranged it.
Most work was debugging why I didn't get the yellow plane, which I saw only once, so I knew it exists.

acoirding the pull request, yes, I saw that it has all previous commits, that's why I asked how you want it (in an github issue). Perhaps you only want to incorporate some of the commits...

**Comment by hg42** [comment]
now the name of the pull request is misleading, hope that's ok for others (if they look at pull requests only).
Seems like it's not possible to rename it?

**Pull request merged**
