### PR TITLE
package.sh: add fedora

### PR DESCRIPTION
**Pull request by fhuberts**
Fedora builds Cura by using `mock`, thereby enabling it to build RPMs
for every distribution that `mock` has a configuration file for. In
pratice this means that Fedora can build RPMs for several versions of
Fedora, CentOS and RHEL.

Cura can be built under a regular user account, there is no need to have
root privileges. In fact, having root privileges is very much discouraged.

However, the user account under which the build is performed needs to be
a member of the 'mock' group.

Specify only 'fedora' to build RPMs for the current system.
  ./package.sh fedora

Additionally specify any number of mock configurations
(ls -1 /etc/mock/*.cfg) to build RPMs for those configurations.
  ./package.sh fedora fedora-21-x86_64.cfg fedora-21-i386.cfg ...

Since only the filename of the mock configurations is used, this
also works:
  ./package.sh fedora /etc/mock/fedora-21-x86_64.cfg ...

Signed-off-by: Ferry Huberts ferry.huberts@pelagic.nl

### CODE REVIEW

**Comment by daid** [comment]
Due to the other package.sh merge I cannot merge this right now (in conflict). But I have no problem in merging this in.

**Comment by fhuberts** [comment]
Rebased.

**Comment by daid** [comment]
And merged.

Note, I also got your message (at least, I assume it was you) from our support department.

Yes, the build scripts of Cura are a mess. You are spot on there. They are in a state of "they work for me", but they are not pretty or well organized, or even that stable or smart. It's one of the places where the "hobby project" origin of Cura really shows.

(Also, not sure what you mean with a "v2 maker"?)

**Comment by fhuberts** [comment]
Thanks!

Yeah that was me.
v2: I meant the extended maker.

Talking from my (Fedora) standpoint:
To improve the build scripts the firmware should also be built in the mock. And they can be built as separate RPMs.

But I'm very happy that you pulled this PR since now I can at least install Cura on my Fedora machine and you can offer the RPMs as well through the website if you want.

Also, I did a very brief try and it also builds for epel7 (which is CentOS7 and RHEL7) and for Fedora 20. Did not test whether they truely run, but at least they build :-)

**Comment by daid** [comment]
The whole package is a big "against the way linux works", due to the whole "everything in a single package way. But it works, and it's little effort to maintain. The engine and the GUI should also be separate packages for example, and the engine is static linked instead of dynamic. It's not pretty, but it works.

(In all honesty, I never test the .deb files that I release on the main site as well, but never got complains about those ;-) )

**Comment by fhuberts** [comment]
Would you mind if I add some things to build RPMs for the firmwares in the firmware repos?

That would allow me to disable building those in package.sh

**Pull request merged**
