### PR TITLE
Fixed Printrbot profiles

### PR DESCRIPTION
**Pull request by adeebshihadeh**
I fixed a few mistakes in the Printrbot profiles. I also removed some redundancies.

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Printrbot LC v1 and Plus v1 prodiles added as well

**Comment by daid** [comment]
Thanks! Got a few complains about them being wrong, but without anyone telling me what the actual mistakes where.

**Comment by adeebshihadeh** [comment]
You can also close issue #1001. I added the changes requested in my last commit which was merged.

**Comment by Cyphrz** [comment]
Just wondering if this is in effect as of 15.02?
Otherwise I will make a new report.

**Comment by adeebshihadeh** [comment]
should be. what's wrong?

**Comment by Cyphrz** [comment]
Simple maker 1405 default http://pastebin.com/bVfNDi7Q
My modified best http://pastebin.com/8uW0vERQ

**Comment by adeebshihadeh** [comment]
The things you changed are completely dependent on your filament and printer. The Simple 1405 profile is meant for the stock printer. The nozzle orifice is 0.4mm by default and not 0.5mm. The 210C printing temp is completely dependent on your hotend and filament. The layer height and fill density are dependent on the model and will vary nearly every print.

**Comment by Cyphrz** [comment]
What I am saying is that the default profile has settings such as the nozzle size as .5 which is wrong.
The filament diameter is wrong too.

I changed it to the proper settings. I think you might have mixed up my settings and the default.

**Comment by adeebshihadeh** [comment]
Did you make a new profile or are you expecting yours to be updated? Check the source. The settings are correct. I had Printrbot confirm them before I submitted the PR.

**Comment by adeebshihadeh** [comment]
Also, when you update I have found Cura to keep the profile name but change all the other settings to some unknown default.

**Comment by Cyphrz** [comment]
It was on a brand new install on my computer. It was from the first run wizard. I will try a complete re-install.

**Pull request merged**
