### PR TITLE
packages.sh: do not use SSH clones, they require keys being setup

### PR DESCRIPTION
**Pull request by fhuberts**
With this patch a build server can just build the project without
generating SSH keys for it and then setting those keys up in
a Github account.

Signed-off-by: Ferry Huberts ferry.huberts@pelagic.nl

### CODE REVIEW

**Comment by daid** [comment]
See other pull requests with the same thing. This is currently required for my release scripts pushing tags.

**Comment by fhuberts** [comment]
Your release scripts can simply do

```
git config remote.origin.pushurl URL
```

in each repo you want to push.

Accepting this PR would make it _much_ easier on downstream/users building your projects... :-)

**Comment by fhuberts** [comment]
I'll update the PR with these push URLs, ready in a minute...

**Comment by fhuberts** [comment]
updated.

this update should address your concerns

**Comment by fhuberts** [comment]
mmm, the update doesn't show, I'll open a new PR

**Pull request closed without merging**
