### PR TITLE
Alternative LPR Backend

### PR DESCRIPTION
**Pull request by greenarrow**
Hi Daid,

Would you mind looking at some patches I have been working on. I have been using an alternative backend to the existing serial comms in Cura.

This backend uses the LPR protocol to send jobs to a 3D print server, namely matterQ (http://matterq.org).

Are alternative backends something you have considered having in Cura? I have implemented lprWindow separate from printWindow as they both do very different things and it makes maintenance easier (whether you decide to merge this into the mainline or whether I maintain a separate branch).

If you get a chance to look I would love to hear your thoughts.

Ta,
Stefan

### CODE REVIEW

**Comment by daid** [comment]
I like the idea. I'm not merging it yet, but that's because I'm very close to a new release.

I was wondering, do you support multiple printers on 1 PI? Because that would be a useful feature ;-)

**Comment by greenarrow** [comment]
Sorry, I meant to reply to a while ago..

At the moment it only supports one printer, I hadn't really thought of more than one but that is a good idea. I've started steering further development in the multi-printer direction.

**Comment by haneefmubarak** [comment]
@greenarrow Did you ever get to finish the multi-printer?

**Comment by greenarrow** [comment]
@haneefmubarak Then next version will support this which should be ready in a couple of weeks.

**Comment by haneefmubarak** [comment]
@greenarrow Tell us when you have committed the multi-printer.

**Comment by haneefmubarak** [comment]
@daid Looks about right, according to @greenarrow in greenarrow/matterQ#2.

**Comment by daid** [comment]
If this is still a request, then it needs to be re-written as a util/printerConnection/printerConnectionBase subclass.

**Pull request closed without merging**
