### PR TITLE
Adding support for saving X3G toolpath for Makerbot printers by using GPX (https://github.com/whpthomas/GPX)

### PR DESCRIPTION
**Pull request by felipesanches**
This allows one to generate Makerbot flavour gcode, convert it to X3G and save it to an SD card for usage in a Replicator 1 without having to use MakerWare or ReplicatorG.

### CODE REVIEW

**Comment by daid** [comment]
Interesting! Good find on the GPX tool. This could change a lot for makerbot users that want to use Cura.

**Comment by felipesanches** [comment]
Is it good for merging, already? Or would you like to provide some feedback on things you'd like to see improved before merging?

**Comment by daid** [comment]
Well, it's guaranteed not to work on Windows right now (will fail to find the executable). The packaging scripts do not include GPX, and I do not think this code belongs in the scene-view but could be better abstracted towards the sliceEngine.py code (where the sliceEngine tells the frontend which file extension to use and how to handle the conversion) but that's a refactoring step, and there is worse code in Cura :-)
GPX also needs configuration which is not handled, which I see as the biggest problem. And I'm not 100% sure how to handle yet.

So the idea is good, but the current implementation would confuse people. As it will fail silently to write a X3G file without manual extra configuration and setup of tools.

**Comment by felipesanches** [comment]
Why did you simply close this? I'm still planning to work on the additional coding to get this done. Please leave this issue open for further brainstorm on the implementation details.

**Comment by nallath** [comment]
The current implementation doesn't work for all platforms, which is sort of a problem. 
I'm also afraid that you will do quite a bit of unneeded work, due to big changes in the GUI (and underlying architecture).
A first stub of the stup can be found in the PinkUnicorn branch. So compared to the 'old' way of doing things, we will have machine objects (and associated Scenes & views) which handle all settings and g-code conversion. A makerbot class would be required for 'proper' conversion to X3G files.

**Pull request closed without merging**
