### PR TITLE
Fix G28 command behaviour from new firmware homing idea

### PR DESCRIPTION
**Pull request by paclema**
G28 X0 Y0 set current position to 0,0 after do homing. It will be more correct if we just made homing.

### CODE REVIEW

**Comment by daid** [comment]
In who's firmware? Cause Marlin certainly does (or should!) not.

**Comment by paclema** [comment]
Marlin firmware. Indeed it does now. The fact is that you just want to do home at start.gcode, but when you said G28 X0 Y0, you force the homing coordinates to 0,0 too.

**Comment by paclema** [comment]
more coments on marlin here: https://github.com/MarlinFirmware/Marlin/issues/1904 https://github.com/MarlinFirmware/Marlin/issues/1942

**Comment by daid** [comment]
This firmware change should be reverted. It's breaking not just my code, it's breaking stuff everywhere and is generally a stupid idea.

**Comment by paclema** [comment]
I agree with you Daid about the constant changes on firmware protocol. We must go to have always the same compatibility with all them. As it was seen on reprap wiki (http://reprap.org/wiki/G-code/es#G28:_Move_to_Origin_.28Home.29) the standtart homming sintaxis said that G28 admits the axis that you want to home as parameter and if you add coordinates, these coordinates are ignored. So then, i thought that it could be great to make this PR that on one hand solve this "issue" on marlin and the other hand remove innecesary parameters code.

**Comment by daid** [comment]
The problem then is, that it's no longer really valid GCode, and future or other firmwares might ignore the axis codes.

**Comment by paclema** [comment]
G28 X Y always be valid gcode (and represents the movement that you want to do at this point,home this axis, not setup 0,0 coordinates on each axis) and the firmware always will home this axis well. G28 X0 Y0 maybe is not a valid gcode, but it works by now

**Comment by daid** [comment]
According to the standard I could find, every "word" is build up from a letter followed by a value. Leaving out the value makes it illegal GCode, even tough most firmwares accept it.

**Pull request closed without merging**
