### PR TITLE
TweakAtZ 3.2

### PR DESCRIPTION
**Pull request by Dim3nsioneer**
- bugfix parser for delta printers
- individual extruder flow
- reset speed after print to 100%
- display message on UM Original

### CODE REVIEW

**Comment by daid** [comment]
Awesome work as always :-)

**Comment by Dim3nsioneer** [comment]
Thanks for the flowers...

**Comment by nallath** [comment]
http://s1.hubimg.com/u/6935834_f520.jpg

**Comment by cederom** [comment]
TANK U! =)

**Comment by Dim3nsioneer** [comment]
@nallath :+1:

**Pull request merged**
