### PR TITLE
punchtec Connect XL machine profile

### PR DESCRIPTION
**Pull request by frivas12**
punchtec's new 3D printer the Connect XL machine profile.  Daid could you please add my machine profile to your next release:)

### CODE REVIEW

**Comment by daid** [comment]
Will be in the next release :D cheers

**Comment by frivas12** [comment]
Thank you for adding my profile so quickly. Do you have any idea when the next release will be?
I need to thank you for such incredible work, I believe you have the best slicer out there. I will make sure to give you credit on my website. Take care and have a nice day.

Thank you,
punchtec
Panchy Rivas, Owner
Sales: Sales@punchtec.com
Support: Support@punchtec.com
Web: http://www.punchtec.com
Skype: punchtec

**Comment by daid** [comment]
I hope to do a new release in the next few weeks. The latest release candidate is available at:
http://software.ultimaker.com/Cura_closed_beta/ (does not include your profile yet, but contains a few bugfixes compared to the current 14.03)

**Comment by frivas12** [comment]
Thanks for the information and have a nice day.

Thank you,
punchtec
Panchy Rivas, Owner
Sales: Sales@punchtec.com
Support: Support@punchtec.com
Web: http://www.punchtec.com
Skype: punchtec

**Pull request merged**
