### PR TITLE
A couple of small changes needed on win32

### PR DESCRIPTION
**Pull request by smorloc**

### CODE REVIEW

**Comment by daid** [comment]
You do need to import power. You need this module: https://github.com/GreatFruitOmsk/Power

**Comment by smorloc** [comment]
If that is the case, shouldn't it be included in the distribution created
by the script 'package.sh'?  If so, I can change the script to include the
power package...

**Comment by daid** [comment]
As we where throwing around code, moving stuff and changing the way Cura was packaged on the Mac, I didn't update the windows package.sh yet.
I'm working towards a release, so the power module will be included in the package.sh soon.

**Comment by smorloc** [comment]
In case it might be useful to you, I have attached a copy of package.sh
that includes the power package.

Do you know if someone has sorted out the Windows Explorer
file associations so that you can double clip on an STL and have it open in
Cura?  This was the primary way I opened STL files so it is unfortunate it
no longer works.

**Comment by Intrinsically-Sublime** [comment]
The linux release of 12.12 will not run either as it expects this module to be included. I commented it out of Cura.sh and the include in whatever file its expected in and it runs without it. After looking into it a little I can not figure out why we would need anything to access the power monitor of our computer in a slicing program.

**Comment by daid** [comment]
The power module is needed for the printing interface, the code is a bit of a mess, so the rest of the GUI also needs it because of that.

The doubleclick STL is a bug, working on it.

**Comment by Intrinsically-Sublime** [comment]
Are you going to update the release version with the power module so people can use it?

**Comment by daid** [comment]
I think the startup script in the linux release tells you that you need the module and from where:
https://github.com/daid/Cura/blob/master/scripts/linux/cura.sh#L28

**Comment by Intrinsically-Sublime** [comment]
Then what do you do with it and where does it go? Also is the release not supposed to be a release that requires no dependencies?

**Comment by daid** [comment]
You install it like any other python package.

The linux package isn't complete. As it's the hardest target to support with the least amount of users.

**Comment by Intrinsically-Sublime** [comment]
No need to install it. Just drop the entire Power folder in the root of Cura with the PyPy  folder and Cura folder and it works. Hope this helps to make the release work for others.

**Comment by AlienTux** [comment]
thank you, I was wondering how to make it work! =] copied the folder, worked like a charm.

**Pull request closed without merging**
