### PR TITLE
Added witbox configuration on first wizard and witbox firmware for install default firmware

### PR DESCRIPTION
**Pull request by paclema**

### CODE REVIEW

**Comment by daid** [comment]
Is the witbox firmware build with customized settings?

**Comment by paclema** [comment]
Of course. Witbox is a new 3d printer made in Navarra (Spain) http://www.bqreaders.com/productos/witbox.html
The firmware is derived from Marlin, but it is a new version. You can take a look of it at https://static-bqreaders.s3.amazonaws.com/file/Witbox/Marlin_Witbox_v1.1.rar

**Comment by daid** [comment]
Then the attribution on the firmware is wrong, which means I cannot merge it like this. As it would violate the GPLv3 license of Marlin.

**Comment by paclema** [comment]
Finally, I'm waiting for the pull request on https://github.com/ErikZalm/Marlin/pull/814.  I wrote to Erikzalm for contribute with my part of code some weeks ago and he told me that if could I make a pull request. Do you think that everything will be ok to accept this pull request if Marlin_v1 accepts too? I want to contribute to the community but I'm learning git ;)

**Pull request closed without merging**
